platform :ios, '9.0'

use_frameworks!
inhibit_all_warnings!

target 'PandaKit_Example' do
  pod 'PandaKit', :path => '../'
  pod 'Kingfisher'
  
  target 'PandaKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
